### ISSUE TITLE
We should add a title page or a separate image of the contributors and their details to the page that would be better.

### ISSUE THREAD

**Issue by Rishita2528** [gitgoap/AI-Snipping-Tool_IIT-D_Hackathon#18]
We should add a title page or a separate image of the contributors and their details to the page that would be better.

_Originally posted by @Rishita2528 in https://github.com/gitgoap/AI-Snipping-Tool_IIT-D_Hackathon/issues/17#issuecomment-2138905632_

**Comment by gitgoap** [comment]
This is not needed as this will create clutter in main files of this repo.
