### ISSUE TITLE
Modifying future scope and features section of read me

### ISSUE THREAD

**Issue by Unnimaya6122004** [gitgoap/AI-Snipping-Tool_IIT-D_Hackathon#19]
need to improve the above mention part of readme..

**Comment by Unnimaya6122004** [comment]
can u pls assign me this issue

**Comment by gitgoap** [comment]
@Unnimaya6122004 
Can you add description detailing how you would modify future scope/features sectio.

**Comment by Unnimaya6122004** [comment]
i mentioning points like
-real time translation of extracted text
-Allow users to save screenshots and summaries to cloud storage services
-voice to text conversion

**Comment by why-aditi** [comment]
Can you assign me this issue?
