### ISSUE TITLE
Feature Addition: Image Capture Preview

### ISSUE THREAD

**Issue by payalsinha12** [gitgoap/AI-Snipping-Tool_IIT-D_Hackathon#25]
Description:
As an enhancement to the AI Screenshot Chrome extension, we propose the addition of a preview feature for captured images. This feature will provide users with visual feedback of the captured screenshot, allowing them to review the image before extracting text using Tesseract OCR. The preview window will display the captured image in a modal or popup, enabling users to verify the accuracy and completeness of the screenshot.

Functionality:

Upon capturing a screenshot using the extension, a preview modal/window will automatically open, displaying the captured image.
Users can zoom in/out, pan, or rotate the image within the preview window to inspect specific areas or details.
The preview window will include controls for confirming the screenshot and proceeding with text extraction or discarding the screenshot if needed.
Additionally, users can have the option to save or download the captured image directly from the preview window for further reference or analysis.
Benefits:

Provides users with visual confirmation of the captured image, enhancing usability and user experience.
Allows users to verify the quality and content of the screenshot before proceeding with text extraction.
Facilitates error detection and correction by enabling users to review and adjust the captured image as necessary.
Implementation:

Modify the extension's logic to display a preview modal/window upon capturing a screenshot.
Use JavaScript and CSS to create an interactive preview interface with zoom, pan, and rotation functionalities.
Implement controls for confirming, discarding, and saving/download options within the preview window.
Test the feature across different browsers and devices to ensure compatibility and responsiveness.  @gitgoap please assign me the project for contribution

**Comment by payalsinha12** [comment]
@gitgoap please assign me the project for the contributions

**Comment by gitgoap** [comment]
@payalsinha12 



From my understanding, you are proposing to add a **1. preview section** and **2. download section.**

I recommend only go with 1 feature that is preview section and _raise another issue for download of screenshot feature._

Make the necessary changes then I'll assign the issue accordingly.
