### ISSUE TITLE
[Readme] Adding an image 

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool_IIT-D_Hackathon#29]
![Screenshot 2024-06-02 195059](https://github.com/gitgoap/AI-Snipping-Tool_IIT-D_Hackathon/assets/117789470/806d324b-2c4d-408d-9f75-cae7b5ab1b29)

- Add this image below `point 6` of *setting up the project locally*
- Keep the dimensions of the image good (not too big/small)

**Comment by hitesh-mehta** [comment]
assign this to me please!

**Comment by gitgoap** [comment]
@hitesh-mehta 
I will assign this issue after resolving PR #21  and #28 in order to avoid any conflict

**Comment by Ishita-2611** [comment]
please assign me this issue. 

![ssoc project](https://github.com/gitgoap/AI-Snipping-Tool_IIT-D_Hackathon/assets/151764416/86da2a4a-8d85-4797-9d68-bc2e8ef40039)
] I have done everything accordingly as u can check

**Comment by gitgoap** [comment]
@hitesh-mehta You are assigned!

**Comment by Amarkr1717** [comment]
please assign this task to me.
