### ISSUE TITLE
[Bug] Typo in the "summerized" button on the Extension popup

### ISSUE THREAD

**Issue by hitesh-mehta** [gitgoap/AI-Snipping-Tool_IIT-D_Hackathon#31]
The word "summarized" should be used instead of the mis-spelt word "summerized" which has another literal meaning.
![image](https://github.com/gitgoap/AI-Snipping-Tool_IIT-D_Hackathon/assets/72137241/e9306b2d-4d1c-439e-a895-bc0aef8665c4)

**Comment by hitesh-mehta** [comment]
can you assign the issue to me?

**Comment by gitgoap** [comment]
This button is removed from the extension, this screenshot is old!
