### ISSUE TITLE
[Feature] Some important UX changes to be made in the buttons available on the popup

### ISSUE THREAD

**Issue by hitesh-mehta** [gitgoap/AI-Snipping-Tool_IIT-D_Hackathon#32]
The following changes must be carried out on the listed popup buttons.
1. Auto Detect (eng) : It should be changed to "Auto-Detect (English)".

**Comment by hitesh-mehta** [comment]
please assign this to me!

**Comment by gitgoap** [comment]
I updated the issue since the summarize button has been removed from the extension.

**Comment by gitgoap** [comment]
Go for it @hitesh-mehta
