### ISSUE TITLE
adding color to text 

### ISSUE THREAD

**Issue by Chelseasingla1** [gitgoap/AI-Snipping-Tool_IIT-D_Hackathon#34]
I would like to add feature to show text with some color to make it more interactive.
![image](https://github.com/gitgoap/AI-Snipping-Tool_IIT-D_Hackathon/assets/129886894/8fee0cba-07e3-40b0-bb93-403bae0913c7)

Please assign me this issue under SSOC'24.

**Comment by gitgoap** [comment]
How will you decide which colour to choose for a particular text? @Chelseasingla1
