### ISSUE TITLE
[Doc update] Addition of developer contribution guidelines 

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool_IIT-D_Hackathon#4]
- Need a **separate** ```contribution.md```  file in this GitHub repo for the developers.
- Take inspiration from [this repo](https://github.com/akshitagupta15june/Moksh/blob/main/Contributing.md)
- keep it short and easy to understand for *beginners*

**Comment by neelamnagarajgithub** [comment]
Can u assign me this issue??

**Comment by gitgoap** [comment]
@neelamnagarajgithub 
You are assigned this issue.
Only submit PR on or after 1st June (starting date of SSOC).

**Comment by gitgoap** [comment]
@neelamnagarajgithub 
Note while raising a P.R. also delete the short 2 lines contribution  guidelines in readme

**Comment by neelamnagarajgithub** [comment]
okay Done✅

**Comment by hitesh-mehta** [comment]
solving #4

**Comment by hitesh-mehta** [comment]
please assign this issue to me!
