### ISSUE TITLE
[Bug] Language Translation fault

### ISSUE THREAD

**Issue by hitesh-mehta** [gitgoap/AI-Snipping-Tool_IIT-D_Hackathon#41]
The language is not geeting translated into the selected one.
![image](https://github.com/gitgoap/AI-Snipping-Tool_IIT-D_Hackathon/assets/72137241/a2187a9a-8b4a-409a-b382-f5a7914e9443)

**Comment by gitgoap** [comment]
@hitesh-mehta 
This is not an intended feature.
The language option given to choose to extract a particular language.

For example, if the screenshot contains Russian text  then we have to choose Russian as an option from drop down then only the tesseract ocr model is able to recognise and extract text correctly.
