### ISSUE TITLE
[Doc] Update screenshots in readme.md file

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool_IIT-D_Hackathon#5]
## Steps to do
- Setup this repo in your system by following the guidelines in readme
- Use this Chrome extension
- Take a screenshot of the tool after use
- Update the ```readme.md``` file

**Comment by Nirvanjha2004** [comment]
Assign this task to me

**Comment by Aditijainnn** [comment]
Please assign me this issue

**Comment by Nirvanjha2004** [comment]
@gitgoap  Sir Its not mentioned in the readme file...how to setup the repo?

**Comment by gitgoap** [comment]
@Nirvanjha2004 
I will update that part in readme today.

**Comment by gitgoap** [comment]
@Nirvanjha2004 What's the status of the work?

**Comment by Nirvanjha2004** [comment]
@gitgoap I raised a PR ...kindly check if any further change is needed..

**Comment by Amarkr1717** [comment]
please assign this issue to me.
