### ISSUE TITLE
Add Code Of Conduct file

### ISSUE THREAD

**Issue by Priyanshu2631** [gitgoap/AI-Snipping-Tool_IIT-D_Hackathon#6]
The repository lacks a Code Of Conduct file which will ensure smooth contribution and collaboration without conflicts,please assign me the issue under SSOC '24

**Comment by gitgoap** [comment]
@Priyanshu2631 Go for it!

**Comment by Priyanshu2631** [comment]
@gitgoap Sir I will raise the PR again after the program starts
