### ISSUE TITLE
Structure the solution section in readme.md

### ISSUE THREAD

**Issue by gitgoap** [gitgoap/AI-Snipping-Tool_IIT-D_Hackathon#8]
## Things to do and keep in mind
 
1. Adjust the non-working links.

 2. Adjust the text with appropriate markdown i.e. *BOLD*, **Italics**, etc making sure that the content remains the same.

**Comment by Priyanshu2631** [comment]
Sir,can I work on this issue

**Comment by Amitanand0123** [comment]
@gitgoap I'm willing to work on this issue. 
I will modify the non -working links and adjust the text size and style appropriately.
![image](https://github.com/gitgoap/AI-Snipping-Tool_IIT-D_Hackathon/assets/140126906/5324a9b3-1abf-49e5-85f1-d6f4479ec0d8)
Like in this section the Title and and content sizes are same. I will modify it.
Thank you :)

**Comment by gitgoap** [comment]
@Priyanshu2631 
You are assigned this issue.
Only submit PR on or after 1st June (starting date of SSOC).

**Comment by mahiv04** [comment]
sir, can I work on this issue

**Comment by hitesh-mehta** [comment]
please assign this issue to me as other two have been already resolved
